#!/bin/sh
#
# MIT License
# Copyright (c) 2017-2020 Nicola Worthington <nicolaw@tfb.net>
#
# https://nicolaw.uk
# https://nicolaw.uk/#TiddlyWiki
#
# Refer to the canonical online documentation for help:
# - https://tiddlywiki.com/static/Using%2520TiddlyWiki%2520on%2520Node.js.html
# - https://tiddlywiki.com/static/ServerCommand.html
#
# Reign in Node memory consumption:
# - https://github.com/nodejs/node/issues/2738
# - https://nodejs.org/api/cli.html#cli_node_options_options
# - http://fiznool.com/blog/2016/10/01/running-a-node-dot-js-app-in-a-low-memory-environment/
#

set -e

main () {
  TW5="$(readlink -f "$(which tiddlywiki)")"
  if [ -n "$NODE_MEM" ]; then
    NODE_OPTIONS="--max_old_space_size=$(( ( NODE_MEM * 4 ) / 5 )) \
                  $NODE_OPTIONS"
    export NODE_OPTIONS
  fi

  if [ ! -d "/var/lib/tiddlywiki/$TW_WIKINAME" ]; then
    /usr/bin/env node "$TW5" "$TW_WIKINAME" --init server
  fi

  # shellcheck disable=SC2086
  exec /usr/bin/env node $NODE_OPTIONS "$TW5" "$TW_WIKINAME" --server \
    "$TW_PORT" \
    "$TW_ROOTTIDDLER" \
    "$TW_RENDERTYPE" \
    "$TW_SERVETYPE" \
    "$TW_USERNAME" \
    "$TW_PASSWORD" \
    "$TW_HOST" \
    "$TW_PATHPREFIX"
}

main "$@"
